[general]
bars = 42
framerate = 60
autosens = 1
overshoot = 20

[input]
method = pulse
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 7
bar_delimiter = 59

[smoothing]
monstercat = 1
waves = 1
gravity = 100
integral = 75
noise_reduction = 45
