# Fish syntax highlighting & pager colors dynamically generated by Matugen

# Syntax Highlighting
set -g fish_color_normal '{{colors.on_surface.default.hex}}'
set -g fish_color_command '{{colors.primary.default.hex}}' --bold
set -g fish_color_keyword '{{colors.secondary.default.hex}}'
set -g fish_color_quote '{{colors.tertiary.default.hex}}'
set -g fish_color_redirection '{{colors.primary_fixed_dim.default.hex}}'
set -g fish_color_end '{{colors.secondary_fixed_dim.default.hex}}'
set -g fish_color_error '{{colors.error.default.hex}}'
set -g fish_color_param '{{colors.on_surface_variant.default.hex}}'
set -g fish_color_comment '{{colors.outline.default.hex}}'
set -g fish_color_selection --background='{{colors.surface_container_highest.default.hex}}'
set -g fish_color_search_match --background='{{colors.surface_container_high.default.hex}}'
set -g fish_color_operator '{{colors.primary.default.hex}}'
set -g fish_color_escape '{{colors.tertiary.default.hex}}'
set -g fish_color_autosuggestion '{{colors.outline.default.hex}}'
set -g fish_color_cancel '{{colors.error.default.hex}}'

# Pager / Completion Colors
set -g fish_pager_color_progress '{{colors.outline.default.hex}}'
set -g fish_pager_color_prefix '{{colors.primary.default.hex}}' --bold
set -g fish_pager_color_completion '{{colors.on_surface.default.hex}}'
set -g fish_pager_color_description '{{colors.on_surface_variant.default.hex}}'
set -g fish_pager_color_selected_background --background='{{colors.surface_container_highest.default.hex}}'
