-- Generated by Matugen for Hyprland Lua
local colors = {
    image = "{{image}}",
<* for name, value in colors *>
    {{name}} = "rgba({{value.default.hex_stripped}}ff)",
<* endfor *>
}

for k, v in pairs(colors) do
    _G[k] = v
end

return colors
