[config]
source_color_index = 0

[config.wallpaper]
# Whether to set the wallpaper or not
set = true

# The command to run for applying the wallpaper in Matugen 4.x
command = "awww img --transition-fps 90 --transition-step 200 --transition-type any {{ image }}"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'
post_hook = 'hyprctl reload 2>/dev/null || true'



[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty 2>/dev/null || true'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/shared/colors.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill waybar; (waybar >/dev/null 2>&1 &)'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/colors.theme'
post_hook = 'pkill -SIGUSR1 btop 2>/dev/null || true'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -R && swaync-client -rs 2>/dev/null || true'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.antigravity]
input_path = '~/.config/matugen/templates/antigravity-colors.json'
output_path = '~/.config/matugen/antigravity-colors.json'
post_hook = 'jq -s ".[0] * {\"workbench.colorCustomizations\": .[1]}" "$HOME/.config/Antigravity IDE/User/settings.json" "$HOME/.config/matugen/antigravity-colors.json" > /tmp/ag_settings.json && cp /tmp/ag_settings.json "$HOME/.config/Antigravity IDE/User/settings.json"'

[templates.fish]
input_path = '~/.config/matugen/templates/fish-colors.fish'
output_path = '~/.config/fish/conf.d/colors.fish'

[templates.fastfetch]
input_path = '~/.config/matugen/templates/fastfetch-config.jsonc'
output_path = '~/.config/fastfetch/config.jsonc'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock-colors.conf'
output_path = '~/.config/hypr/colors.conf'

